name: flutter_weater_forecast
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  d_input: ^0.1.1
  d_view: ^0.0.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  extended_image: ^8.1.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  d_method: ^0.2.1
  grouped_list: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  mocktail: ^1.0.1
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
